spring.application.name=AuthService-Library
server.servlet.context-path=/auth/v1


jwt.secret=qzErqlGgQr8EXV/+T23pcHi5y4ZPsm05IQfzaKx5zTU=


# Connection URL, username, and password
spring.datasource.url=jdbc:postgresql://localhost:5432/users
spring.datasource.username=postgres
spring.datasource.password=Pass@123
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=users
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true




# Actuator - expose health endpoint only
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

# Change the default Swagger UI path (Default is /swagger-ui/index.html)
springdoc.swagger-ui.path=/swagger-ui.html

